version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: deployment/docker/api.Dockerfile
    env_file:
      - .env
    ports: ["8000:8000"]
    depends_on: [db]

  ingestion:
    build:
      context: .
      dockerfile: deployment/docker/ingestion.Dockerfile
    env_file: [.env]
    depends_on: [db]

  grafana:
    image: grafana/grafana:11.0.0
    ports: ["3000:3000"]
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports: ["9090:9090"]

volumes:
  db_data:
